display_name: hdict
package_name: hdict
maintainer:
  name: Dr. Dhaval Patel
  email: drdhaval2785@gmail.com
installed_size: 6604
icon: assets/hdict_logo.png
summary: Dictionary Reader App for StarDict, Dictd, Slob and Mdict dictionaries
license: GPL-3.0
url: https://github.com/drdhaval2785/hdict
architecture: x86_64
keywords:
  - Dictionary
  - StarDict
  - Dictd
  - Slob
  - Mdict
generic_name: Dictionary Reader
categories:
  - Utility
startup_notify: true