icon: assets/hdict_logo.png
summary: Dictionary Reader App for StarDict, Dictd, Slob and Mdict dictionaries
group: Application
vendor: Dhaval
license: GPL-3.0
url: https://github.com/drdhaval2785/hdict
display_name: hdict
keywords:
  - Dictionary
  - StarDict
  - Dictd
  - Slob
  - Mdict
generic_name: Dictionary Reader
categories:
  - Utility
startup_notify: true