display_name: hdict
icon: assets/hdict_logo.png
generic_name: Dictionary Reader
keywords:
  - Dictionary
  - StarDict
  - Dictd
  - Slob
  - Mdict
categories:
  - Utility
startup_notify: true
update_info: gh-releases-zsync|drdhaval2785|hdict|latest|hdict-*-x86_64.AppImage.zsync