#!/usr/bin/env python3
"""
Compare documentation with api_documentation.md as source of truth.

This script reads api_documentation.md (generated by Dart Analyzer) and checks
whether everything is documented in public.md and private.md.
"""

import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
REFERENCE_DIR = PROJECT_ROOT / "reference"


def parse_api_doc():
    """Parse api_documentation.md and extract all API elements."""
    api_doc_path = REFERENCE_DIR / "api_documentation.md"
    if not api_doc_path.exists():
        print("ERROR: api_documentation.md not found!")
        return None

    content = api_doc_path.read_text()

    api_data = {
        'files': {},
    }

    current_file = None
    current_class = None
    current_type = None  # 'class', 'enum', or None
    current_section = None

    lines = content.split('\n')
    i = 0
    while i < len(lines):
        line = lines[i].strip()

        # File header
        if line.startswith('## File: `'):
            file_match = re.match(r'## File: `([^`]+)`', line)
            if file_match:
                current_file = file_match.group(1)
                current_class = None
                current_type = None
                if current_file not in api_data['files']:
                    api_data['files'][current_file] = {
                        'enums': {},
                        'classes': {},
                        'functions': [],
                    }

        # Class header
        elif line.startswith('### Class: `'):
            class_match = re.match(r'### Class: `([^`]+)`', line)
            if class_match:
                current_class = class_match.group(1)
                current_type = 'class'
                current_section = None
                if current_file:
                    if current_class not in api_data['files'][current_file]['classes']:
                        api_data['files'][current_file]['classes'][current_class] = {
                            'fields': [],
                            'constructors': [],
                            'methods': [],
                            'properties': [],
                        }

        # Enum header
        elif line.startswith('### Enum: `'):
            enum_match = re.match(r'### Enum: `([^`]+)`', line)
            if enum_match:
                current_class = enum_match.group(1)
                current_type = 'enum'
                current_section = None
                if current_file:
                    if current_class not in api_data['files'][current_file]['enums']:
                        api_data['files'][current_file]['enums'][current_class] = {
                            'constants': [],
                            'fields': [],
                            'methods': [],
                        }

        # Section headers
        elif line.startswith('#### '):
            section = line[5:].strip()
            current_section = section

        # Function header
        elif line.startswith('### Function: `') and current_file:
            func_match = re.match(r'### Function: `([^`]+)`', line)
            if func_match:
                func_name = func_match.group(1)
                params = extract_params(lines, i)
                api_data['files'][current_file]['functions'].append({
                    'name': func_name,
                    'params': params,
                })

        # Parse fields (applies to both classes and enums)
        elif line.startswith('- Field: `') and current_file and current_class:
            field_match = re.match(r'- Field: `(.+)`', line)
            if field_match:
                field_str = field_match.group(1)
                if current_type == 'class':
                    api_data['files'][current_file]['classes'][current_class]['fields'].append(field_str)
                elif current_type == 'enum':
                    api_data['files'][current_file]['enums'][current_class]['fields'].append(field_str)

        # Parse constructors
        elif line.startswith('- Constructor: `') and current_file and current_class and current_type == 'class':
            ctor_match = re.match(r'- Constructor: `(.+)`', line)
            if ctor_match:
                api_data['files'][current_file]['classes'][current_class]['constructors'].append(ctor_match.group(1))

        # Parse methods
        elif line.startswith('- Method: `') and current_file and current_class:
            method_sig = extract_full_method_signature(lines, i)
            if method_sig:
                params = extract_params(lines, i)
                if current_type == 'class':
                    api_data['files'][current_file]['classes'][current_class]['methods'].append({
                        'name': method_sig,
                        'params': params,
                    })
                elif current_type == 'enum':
                    api_data['files'][current_file]['enums'][current_class]['methods'].append(method_sig)

        # Parse properties (classes only)
        elif line.startswith('- Property: `') and current_file and current_class and current_type == 'class':
            prop_match = re.match(r'- Property: `(.+)`', line)
            if prop_match:
                api_data['files'][current_file]['classes'][current_class]['properties'].append(prop_match.group(1))

        # Parse enum constants
        elif line.startswith('- `') and current_section == 'Constants' and current_file and current_class and current_type == 'enum':
            const_match = re.match(r'- `([^`]+)`', line)
            if const_match:
                api_data['files'][current_file]['enums'][current_class]['constants'].append(const_match.group(1))

        i += 1

    return api_data


def extract_params(lines, start_idx):
    """Extract parameter names from method/function definition."""
    params = []
    for i in range(start_idx, min(start_idx + 50, len(lines))):
        line = lines[i].strip()
        if line.startswith('- Method:') or line.startswith('- Property:') or line.startswith('- Field:') or line.startswith('####') or line.startswith('### ') or line.startswith('## '):
            break
        if '- Parameter:' in line:
            param_match = re.search(r'- Parameter: `([^`]+)`', line)
            if param_match:
                params.append(param_match.group(1))
    return params


def extract_full_method_signature(lines, start_idx):
    """Extract the full method signature, handling multi-line signatures."""
    sig_parts = []
    i = start_idx
    while i < len(lines):
        line = lines[i].rstrip()
        
        # Check if this is a method line we should process
        if line.startswith('- Method: `'):
            # Find the backtick start
            backtick_idx = line.find('`')
            if backtick_idx != -1:
                content = line[backtick_idx+1:]
                if '`' in content:
                    # Signature ends on this line
                    sig_parts.append(content.split('`')[0])
                    break
                else:
                    # Multi-line, add content
                    sig_parts.append(content)
        elif sig_parts:
            # We're in multi-line mode, check if we've reached the end
            if line.startswith('- Method:') or line.startswith('- Property:') or line.startswith('- Field:') or line.startswith('- Constructor:') or line.startswith('####') or line.startswith('### ') or line.startswith('## '):
                break
            if '- Parameter:' in line:
                # Parameters start on next line - end of signature
                break
            # Otherwise continue collecting (might be continuation of params or something else)
        else:
            # Not a method line and no sig_parts yet - might be a different section
            break
        
        i += 1
    return ''.join(sig_parts) if sig_parts else None


def is_private(name):
    """Check if a name is private (starts with underscore)."""
    return name.startswith('_')


def extract_name_from_signature(sig):
    """Extract the name from a field/method/property signature."""
    sig = sig.strip()
    sig = re.sub(r'^(static\s+|final\s+|const\s+|late\s+|abstract\s+)+', '', sig)
    
    # Skip function type parameters (e.g., "void Function(String) callback")
    if 'Function(' in sig or sig.startswith('Function'):
        return None
    
    # Find where the method name is - look for word followed by ( or get/set
    # But exclude type keywords that precede the method name
    method_match = re.search(r'\s+(\w+)\s*\(', sig)
    if method_match:
        name = method_match.group(1)
        # Skip common type keywords
        if name.lower() in ('void', 'int', 'string', 'bool', 'double', 'future', 'stream', 'list', 'map', 'set'):
            return None
        return name
    
    # For properties (get/set)
    prop_match = re.search(r'\s+(get|set)\s+(\w+)', sig)
    if prop_match:
        return prop_match.group(2)
    
    # For signatures without () - find the last word before any param
    if '(' in sig:
        before_parens = sig.split('(')[0].strip()
        return before_parens.split()[-1] if before_parens.split() else sig
    
    # For properties without get/set - find the last word
    words = sig.split()
    return words[-1] if words else sig


def extract_func_name_from_signature(sig):
    """Extract the function name from a full function signature like 'List<int> _decompressGzip(List<int> bytes)'."""
    sig = sig.strip()
    # Skip function type parameters
    if 'Function(' in sig or sig.startswith('Function'):
        return None
    # Find the name followed by (
    match = re.search(r'\s+(\w+)\s*\(', sig)
    if match:
        name = match.group(1)
        if name.lower() in ('void', 'int', 'string', 'bool', 'double', 'future', 'stream', 'list', 'map', 'set', 'nullable'):
            return None
        return name
    return None


def parse_documentation_file(path):
    """Parse a documentation file and extract documented items."""
    if not path.exists():
        return set(), set(), set(), set()

    content = path.read_text()
    classes = set()
    enums = set()
    methods = set()
    fields = set()

    # Extract class names
    for m in re.finditer(r'### Class: `(\w+)`', content):
        classes.add(m.group(1))
    for m in re.finditer(r'### Private Class: `(_\w+)`', content):
        classes.add(m.group(1))

    # Extract enum names
    for m in re.finditer(r'### Enum: `(\w+)`', content):
        enums.add(m.group(1))
    for m in re.finditer(r'### Private Enum: `(_\w+)`', content):
        enums.add(m.group(1))

    # Extract methods from simple format: - Method: `returnType methodName(`
    for m in re.finditer(r'- Method: `[^`]*\s+(\w+)\s*\(', content):
        methods.add(m.group(1))

    # Extract methods from rich format: ##### Method: `methodName`
    for m in re.finditer(r'##### Method: `(\w+)`', content):
        methods.add(m.group(1))

    # Extract methods from rich format with Static prefix: ##### Static Method: `methodName`
    for m in re.finditer(r'##### Static Method: `(\w+)`', content):
        methods.add(m.group(1))

    # Extract methods from rich format with class prefix: ##### Method: `ClassName.methodName`
    for m in re.finditer(r'##### Method: `[^.]+\.(\w+)`', content):
        methods.add(m.group(1))

    # Extract properties from simple format: - Property: `type get property`
    for m in re.finditer(r'- Property: `[^`]*\s+get\s+(\w+)', content):
        fields.add(m.group(1))

    # Extract properties from rich format: ##### Property: `propertyName`
    for m in re.finditer(r'##### Property: `(\w+)`', content):
        fields.add(m.group(1))

    # Extract properties from rich format with Static prefix: ##### Static Property: `propertyName`
    for m in re.finditer(r'##### Static Property: `(\w+)`', content):
        fields.add(m.group(1))

    # Extract functions from rich format: #### Function: `functionName`
    for m in re.finditer(r'#### Function: `(\w+)`', content):
        methods.add(m.group(1))

    # Extract fields from simple format: - Field: `type field`
    for m in re.finditer(r'- Field: `[^`]*\s+(\w+)`', content):
        name = m.group(1)
        if not name.startswith('_'):
            fields.add(name)

    # Extract fields from table format: | `fieldName` | type |
    for m in re.finditer(r'\| `(\w+)` \|[^|]*\|', content):
        name = m.group(1)
        if not name.startswith('_'):
            fields.add(name)

    # Extract fields from rich format: ##### Field: `fieldName`
    for m in re.finditer(r'##### Field: `(\w+)`', content):
        name = m.group(1)
        if not name.startswith('_'):
            fields.add(name)

    # Extract constructors from rich format: ##### Constructor
    for m in re.finditer(r'##### Constructor', content):
        methods.add('<init>')

    return classes, enums, methods, fields


def compare_apis(api_data, pub_classes, pub_enums, pub_methods, pub_fields,
                  priv_classes, priv_enums, priv_methods, priv_fields):
    """Compare API data against documentation."""
    issues = []

    for file_path, file_data in sorted(api_data['files'].items()):
        file_issues = {'missing_public': [], 'missing_private': []}

        # Check enums
        for enum_name, enum_data in file_data['enums'].items():
            priv = is_private(enum_name)
            target_enums = priv_enums if priv else pub_enums

            if enum_name not in target_enums:
                file_issues['missing_private' if priv else 'missing_public'].append(f"Enum: {enum_name}")

            # Check enum constants
            for const in enum_data.get('constants', []):
                const_name = const.strip()
                if const_name.startswith('_'):
                    continue  # Private constants might not need docs
                if priv and const_name not in priv_fields:
                    file_issues['missing_private'].append(f"  Constant: {const_name} (in {enum_name})")

            # Check enum fields
            for field in enum_data.get('fields', []):
                field_name = extract_name_from_signature(field)
                if field_name.startswith('_'):
                    continue
                if priv and field_name not in priv_fields:
                    file_issues['missing_private'].append(f"  Field: {field_name} (in {enum_name})")
                elif not priv and field_name not in pub_fields:
                    file_issues['missing_public'].append(f"  Field: {field_name} (in {enum_name})")

            # Check enum methods
            for method in enum_data.get('methods', []):
                method_sig = method.strip() if isinstance(method, str) else method.get('name', '')
                method_name = extract_name_from_signature(method_sig)
                if not method_name:
                    continue
                if method_name.startswith('_'):
                    continue
                if priv and method_name not in priv_methods:
                    file_issues['missing_private'].append(f"  Method: {method_name} (in {enum_name})")
                elif not priv and method_name not in pub_methods:
                    file_issues['missing_public'].append(f"  Method: {method_name} (in {enum_name})")

        # Check classes
        for class_name, class_data in file_data['classes'].items():
            priv = is_private(class_name)
            target_classes = priv_classes if priv else pub_classes

            if class_name not in target_classes:
                file_issues['missing_private' if priv else 'missing_public'].append(f"Class: {class_name}")

            # Check fields
            for field in class_data.get('fields', []):
                field_name = extract_name_from_signature(field)
                if not field_name:  # Skip function type parameters
                    continue
                if field_name.startswith('_'):
                    continue
                if priv and field_name not in priv_fields:
                    file_issues['missing_private'].append(f"  Field: {field_name} (in {class_name})")
                elif not priv and field_name not in pub_fields:
                    file_issues['missing_public'].append(f"  Field: {field_name} (in {class_name})")

            # Check constructors
            for ctor in class_data.get('constructors', []):
                ctor_name = extract_name_from_signature(ctor)
                if ctor_name and ctor_name.startswith('_') and ctor_name not in priv_methods:
                    file_issues['missing_private'].append(f"  Private constructor: {ctor_name} (in {class_name})")

            # Check methods
            for method in class_data.get('methods', []):
                method_sig = method['name'] if isinstance(method, dict) else method
                method_name = extract_name_from_signature(method_sig)
                if not method_name:  # Skip function type parameters
                    continue
                if method_name.startswith('_'):
                    continue  # Skip private methods
                if priv and method_name not in priv_methods:
                    file_issues['missing_private'].append(f"  Method: {method_name} (in {class_name})")
                elif not priv and method_name not in pub_methods:
                    file_issues['missing_public'].append(f"  Method: {method_name} (in {class_name})")

            # Check properties
            for prop in class_data.get('properties', []):
                prop_name = extract_name_from_signature(prop)
                if not prop_name:  # Skip function type parameters
                    continue
                if prop_name.startswith('_'):
                    continue
                if priv and prop_name not in priv_fields:
                    file_issues['missing_private'].append(f"  Property: {prop_name} (in {class_name})")
                elif not priv and prop_name not in pub_fields:
                    file_issues['missing_public'].append(f"  Property: {prop_name} (in {class_name})")

        # Check functions
        for func in file_data.get('functions', []):
            func_sig = func['name']
            func_name = extract_func_name_from_signature(func_sig)
            if not func_name:
                continue  # Skip function type parameters
            if func_name.startswith('_'):
                # Private functions should be in private.md
                if func_name not in priv_methods:
                    file_issues['missing_private'].append(f"Function: {func_name}")
            elif func_name not in pub_methods:
                file_issues['missing_public'].append(f"Function: {func_name}")

        if any(file_issues.values()):
            issues.append((file_path, file_issues))

    return issues


def main():
    print("=" * 80)
    print("COMPARING API DOCUMENTATION vs CODE")
    print("=" * 80)

    print("\n[1/3] Parsing api_documentation.md...")
    api_data = parse_api_doc()
    if not api_data:
        return

    total_classes = sum(len(f['classes']) for f in api_data['files'].values())
    total_enums = sum(len(f['enums']) for f in api_data['files'].values())
    total_functions = sum(len(f['functions']) for f in api_data['files'].values())
    print(f"  Found: {total_classes} classes, {total_enums} enums, {total_functions} functions")

    print("\n[2/3] Parsing public.md and private.md...")
    pub_classes, pub_enums, pub_methods, pub_fields = parse_documentation_file(REFERENCE_DIR / "public.md")
    priv_classes, priv_enums, priv_methods, priv_fields = parse_documentation_file(REFERENCE_DIR / "private.md")

    print(f"  public.md: {len(pub_classes)} classes, {len(pub_enums)} enums, {len(pub_methods)} methods, {len(pub_fields)} fields")
    print(f"  private.md: {len(priv_classes)} classes, {len(priv_enums)} enums, {len(priv_methods)} methods, {len(priv_fields)} fields")

    print("\n[3/3] Comparing...")
    issues = compare_apis(api_data, pub_classes, pub_enums, pub_methods, pub_fields,
                          priv_classes, priv_enums, priv_methods, priv_fields)

    print("\n" + "=" * 80)
    print("RESULTS")
    print("=" * 80)

    if not issues:
        print("\nALL API ELEMENTS ARE DOCUMENTED!")
        return

    total_missing_public = 0
    total_missing_private = 0

    for file_path, file_issues in issues:
        print(f"\n{file_path}")

        missing_public = file_issues['missing_public']
        missing_private = file_issues['missing_private']

        if missing_public:
            print(f"\n  MISSING in public.md ({len(missing_public)} items):")
            for item in missing_public[:30]:
                print(f"    - {item}")
            if len(missing_public) > 30:
                print(f"    ... and {len(missing_public) - 30} more")
            total_missing_public += len(missing_public)

        if missing_private:
            print(f"\n  MISSING in private.md ({len(missing_private)} items):")
            for item in missing_private[:30]:
                print(f"    - {item}")
            if len(missing_private) > 30:
                print(f"    ... and {len(missing_private) - 30} more")
            total_missing_private += len(missing_private)

    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print(f"Missing in public.md: {total_missing_public} items")
    print(f"Missing in private.md: {total_missing_private} items")
    print(f"Total missing: {total_missing_public + total_missing_private} items")


if __name__ == "__main__":
    main()
