display_name: hdict
package_name: hdict
maintainer:
  name: Dhaval
  email: drdhaval2785@gmail.com
license: GPL-3.0
priority: optional
section: x11
essential: false
icon: assets/hdict_logo.png
installed_size: 50000
summary: Dictionary Reader App for StarDict, Dictd, Slob and Mdict dictionaries
categories:
  - Utility