name: hdict
title: hdict
adopt-info: hdict
summary: High-performance, feature-rich dictionary reader application
description: |
  A high-performance, feature-rich dictionary application built with Flutter. 
  Optimized for speed, highly customizable, and designed for a premium user experience across all platforms.
  Supports StarDict, MDict, Dictd and Slob formats with universal tap-to-lookup functionality.

contact: https://github.com/drdhaval2785/hdict/issues
license: GPL-3.0
issues: https://github.com/drdhaval2785/hdict/issues
donation: https://paypal.me/drdhaval2785/10USD
source-code: https://github.com/drdhaval2785/hdict
website: https://github.com/drdhaval2785/hdict

confinement: strict
base: core22
grade: stable

apps:
  hdict:
    command: hdict
    extensions: [gnome]
    plugs:
    - network
    - home
    desktop: snap/gui/hdict.desktop

parts:
  hdict:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - clang
      - lld
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      - llvm
      - libstdc++-12-dev # Helps with modern Flutter engine requirements
    override-pull: |
      craftctl default
      craftctl set version=$(grep "^version: " pubspec.yaml | cut -d " " -f 2 | cut -d "+" -f 1)

lint:
  ignore:
    - unused-library:
        - lib/libflutter_7zip.so
